### ISSUE TITLE
Resources page

### ISSUE THREAD

**Issue by Ffisegydd** [sopython/sopython-site#10]
A suggestion originally made by @DarkCrowz on the Trello page:

A lot of people might be looking for resources or libraries to accomplish a specific task. For example, if someone wants to make a web application, it would be good to point them to Flask or Django official documentation. If someone wants to make a game, point them to some pygame tutorials.

Perhaps leverage tags for this to make a dynamically filterable set of resources that is easily linkable.

**Comment by davidism** [comment]
I think this is being handled organically.  The wiki will probably be expanded to cover the "static" pages too, so this will already be in the right place.
