### ISSUE TITLE
Increase paginate size to 100 for CQs

### ISSUE THREAD

**Issue by joncle** [sopython/sopython-site#151]
... we've got the awesome search feature, but if you can't remember (or not sure) what tag/term to search for, sometimes it's a bit annoying to have to paginate through the list 20 at a time... 

What do we think about 100 (we've only got 69 at the moment) for now? It's not exactly a large page - and it shouldn't be a big hit on the DB and will make a quick scrolling down and finding a canonical a bit more expedient?

**Comment by NotTheEconomist** [comment]
Agreed completely! Searching through the CQs page can be a bit of a bear anyway. At least let me Ctrl+F after the built-in search! :+1:

**Comment by AlexFrazer** [comment]
Can we use `select2` for tag searching? I know we like to keep things minimal but it seems the right tool for the job.

https://select2.github.io/
