### ISSUE TITLE
sopython rules re-design

### ISSUE THREAD

**Issue by Ffisegydd** [sopython/sopython-site#156]
Ideas welcome for re-designing the sopython rules page!
- Tidy up the rules.
- Add a "no solicitation" rule.
- Remove "don't ask to ask", and "don't ask who knows something"

**Comment by poke** [comment]
WIP on the wiki: http://sopython.com/wiki/New_rules_page_%28WIP%29

**Comment by rsnape** [comment]
I support removing "don't ask to ask" and "don't ask who knows".  Not sure what you mean about "no solicitation" - don't tout for business?  Soliciting has, erm, questionable connotations to my ear, so I wouldn't use that word itself.  Thoughts on adding a list to the help vampire link that gets pointed to do fairly frequently?  I think it would shortcut a fair amount, as well as performing the "who has read the rules" semaphore function.  Happy to draft something if it's welcome.

**Comment by ztane** [comment]
I **do not** support removing don't ask and don't ask who knows. It is annoying as hell every time a n00b asks it. I feel like I'd want to close the damn chat right away.

**Comment by IntrepidBrit** [comment]
But is it a kick-able offence? It's annoying, but surely that's more of a 'guideline' than a hard rule.

**Comment by ztane** [comment]
Guideline yes, certainly not kickable either but something to back it up so that can complain to newbs that it has been recommended for ages and not something I invented 5 seconds before.

**Comment by PM2Ring** [comment]
My take on the "asking to ask" issue is that it's **not** just about superfluous noise. When someone comes in and says "Can I ask about X?" or even worse "Who knows about X?" there's a good chance that they're a HV and they will latch on to whoever responds to them. So I think we need something to help prevent / reduce that. As I said (belatedly) during the meeting: [meeting](http://chat.stackoverflow.com/transcript/6?m=29929416#29929416): 

I'd like an explicit rule in Asking Questions: "Please don't target your question to an individual unless you are continuing a previous discussion with them. Just ask your question and let whoever wants to answer do so". Hopefully, that will help prevent HVs from latching onto a victim. 

So I'd like to replace or supplement the current  "asking to ask" stuff with something in that vein.

**Comment by AlexFrazer** [comment]
I'd do that sometimes ._. but I think it is probably the most commonly "violated" rule of every on the list.

**Comment by tristanfisher** [comment]
I support keeping the guideline of "don't ask to ask a question. just ask it".

I can understand why users want to @ mention users in chat (after being responded to) -- twitter has taught newbies that this is how you maintain a flow of conversation, and/or, in a busy IRC channel, this is how you maintain a conversation in a busy stream of text.  

I only see this as a problem as the SO chat is not well-featured and doesn't support adjusting the volume of the _ping_ sound or receiving them in a digest (e.g. no more than 1 ping per 10 seconds). 

I do think that we should remove the "be nice" rule.  There's an inverse relationship between word count/users reading the rules and I don't think it adds anything valuable.

**Comment by AlexFrazer** [comment]
why not separate the rules into "etiquette" and "rules", like [the js room has](https://javascriptroom.github.io/rules/#etiquette)?

**Comment by gamesbrainiac** [comment]
I agree with Alex's suggestion.

**Comment by tristanfisher** [comment]
The etiquette is actually just more rules by a different name.  Also, their page is far more words than anyone will read (did you actually finish reading it? would you lie to me?).

**Comment by AlexFrazer** [comment]
yeah it totally is too many words, but a short etiquette section and a short rules section would be nice. Rules seems to be somewhat "harsh" sounding, like something you could get kicked or silenced for. Etiquette is just "this is how the room works". For example

### Rules

1. Don't post links to recently asked questions

### Etiquette

1. Don't ask to ask or ask if anyone knows about a subject. Just ask your question, and if anyone knows, they will answer.

**Comment by tristanfisher** [comment]
And what are the consequences if someone repeatedly breaks the "etiquette"? 

I'm fully behind few enough rule-words that they fit in the room info box.

**Comment by ztane** [comment]
Rule 2: Follow the etiquette

**Comment by IntrepidBrit** [comment]
The same thing as would happen in real life. If someone doesn't follow the established etiquette, then they tend to be sidelined/ignored.

**Comment by davidism** [comment]
We should still include "don't post recent questions" section, as well as explaining that messages like that will be trashed.  Maybe expand on *why* we say that, since we end up explaining it every time.  "Anyone interested in answering is already watching the tag.  Be patient."

**Comment by tristanfisher** [comment]
"No recent questions" is an interesting rule as it can end up punishing people that bothered to explain themselves in the site-question format; I can either ask a lazy question in the room and get an answer _or_ I can post on the site, get downvoted, and ask in the room in 48 hours.

What are we trying to accomplish with the rules rewrite and how do we ultimately decide what the room rules will be?  We demonstrably have different notions of what the rules should be (e.g. I think the rules should fit in the room info box and others believe we should have hundreds of words about etiquette).

**Comment by oceanhahn** [comment]
"No recent questions" might make more sense as "Wait before linking new questions," since it differentiates between posting questions to the main site after asking them (to inadequate effect) and linking to a question you just asked in chat. 

Naturally, it makes sense that nobody would be penalized for posting a question to the main site that goes unanswered in chat (or for posting a question that was properly answered in chat, that is worthy of reporting), but I also think that if it's going to be a rule, the wording ought to be as clear as possible.

I disagree that everyone who might answer a question will already be monitoring the tag, but I can also see how it would irritate people who _do_ monitor both.

**Comment by ztane** [comment]
And it should actually be [wait before *asking for answers to your* recent question in the room]. The truth is there is a sh*tload of more people answering in [python] than those present in the room, the 24 or 48 hours we had explicitly before was because there were people who linked the question after 3 minutes saying "hey can you answer my question". There is nothing wrong in linking your question and asking "is this question unclear", or "Ok, as per our discussion here, I've written this question". 

Requesting answers is what makes it annoying. The people who come to the chat and request this are usually n00bs with utterly uninteresting and unclear questions that could be answered by reading the python tutorial.

**Comment by davidism** [comment]
I agree with @ztane, we should be able to help while avoiding the real problem.  What we need is an explanation of "how to ask about your question", just like main has "how to ask".

> * Wait at least X hours before asking for help
> * Ask about improving your question, don't ask for answers.
> * Explain why you need help if there are already answers / comments.
> * Read the MCVE and XY problem articles
> * Don't onebox it (this could wait until we could automate replacement with rabbit)
>
> If you don't follow these guidelines, your question may be removed.

We still need *some* waiting period; "be patient, plenty of people are following the tag" is still good advice.

I'm worried that vampires will say "I was asking how to improve, not for answers" just as an excuse, but I guess ROs still have discretion to handle that.

**Comment by AlexFrazer** [comment]
What if RABBIT was able to reject very recent posts posted by the same user? I mean as in like. Under 3 hours. That's usually help vampires.
Might be a dumb idea, but what do you guys think?

**Comment by davidism** [comment]
I'm not too concerned with automating it right now.  It would have to be a little more complex than that because if they ask a question based on a discussion we're ok with them posting it.

**Comment by davidism** [comment]
Which brings up another opportunity for RO assistance.  I used to look up the last question a new user asked on main when they joined.  Occasionally a user would try to ask about their question without posting it.  Adding a userscript that adds this and other RO-relevant information to the user menu is something I've been thinking about for a long time, but belongs in its own discussion.

**Comment by Bhargav-Rao** [comment]
I agree with @ztane's message. The many reasons why linking a recently asked question is useless for the poster is that

1. As mentioned before, the users of the room will already have taken a look at the question as we all keep an active tab of the incoming questions.
2. The users of the room will have an undue advantage over the other general answerers as they have an opportunity to chat with that particular poster.
3. Depending on the  question that the OP has posted, it may receive a flood of down votes and close votes and *may* end up with the Poster getting a question ban. 

Though there may be some situations where posting a newly linked question might help, but such situations are quite scarce. In most of the situations the poster might have already found a solution on the main site and will have to concentrate on two parallel conversations (which causes needless conundrums). Hence it is *more* advantageous for the poster to *not link* the question.
