### ISSUE TITLE
Incorrect menu selection when visiting spoiler encoding page:

### ISSUE THREAD

**Issue by IntrepidBrit** [sopython/sopython-site#162]
Relatively minor issue - when visiting the http://sopython.com/spoiler/ , "Salad Language" is selected as the default header menu item.

![screenshot](https://cloud.githubusercontent.com/assets/1637976/15646262/a0eff7b0-2654-11e6-9f1b-a08a20956c56.png)

**Comment by Ffisegydd** [comment]
I didn't even realise the spoiler page had gone live as there wasn't a menu option to begin with.

Really cool idea though.

**Comment by Devious-Mark** [comment]
I think it's a nifty little feature, simple yet effective

**Comment by IntrepidBrit** [comment]
I think it's a nifty little feature, simple yet effective

**Comment by davidism** [comment]
That's what I get for copy pasting. There's a link on the chatroom page but no menu item.
