### ISSUE TITLE
Most pages display user name along with user id

### ISSUE THREAD

**Issue by vaultah** [sopython/sopython-site#164]
[This](https://github.com/sopython/sopython-site/commit/739233e699418c34b007092e43e70850b5a51cd8) commit changed `__str__` to return both `id` and `display_name`. As far as I can tell, that change has a side effect:

> Last edited on Sep 12, 2015, 5:05:22 PM by 1426065 MattDMo

It doesn't look like a desirable behaviour, so it may well be a bug.

**Comment by davidism** [comment]
Yeah, that was my bad.  I'll get to this when I get to removing the PyCon notice.

**Comment by joncle** [comment]
@davidism maybe change the pycon notice to reflect the UK one coming up instead of removing it?
