### ISSUE TITLE
Prevent stripping of leading indentation in spoiler that begins with a code block

### ISSUE THREAD

**Issue by kms70847** [sopython/sopython-site#169]
Suppose the user wishes to publish this spoiler as a code block:

```
>>> print("Hello, world!")
Hello, world!
```

He goes to https://sopython.com/spoiler/ and enters his text, indenting each line by four spaces. He clicks "encode" and gets this link:

https://sopython.com/spoiler/Pj4-IHByaW50KCJIZWxsbywgd29ybGQhIikNCiAgICBIZWxsbywgd29ybGQh

The markup engine interprets `>>> print("Hello, world!")` as a quote instead of code, because the leading four spaces were stripped before parsing.

Currently the user can work around this by adding a line of non-code-block text at the head of his spoiler, for example:
```
Here is my Hello World program:

    >>> print("Hello, world!")
    Hello, world!
```

... But ideally we should not require users to increase the size of their messages to get them to render properly, since spoiler links are often used in a context where character count matters.

**Comment by kms70847** [comment]
I have no way of testing it, but I expect this could be addressed by creating a new class in sopy/ext/forms.py:

    class StripTrailingStringField(StringField):
        """String field that strips trailing whitespace before validating."""

        def process_formdata(self, valuelist):
            self.data = valuelist[0].rstrip() if valuelist else ''

            if not self.data:
                self.raw_data = []

... And using that in place of `StripTextAreaField` in sopy/spoiler/forms.py.

I'll try to compose a pull request if I can remember how to do so.

**Comment by davidism** [comment]
You can just use `TextAreaField` instead of `StripTextAreaField`, no need to make another class.
