### ISSUE TITLE
Invalid certificate, content is 404

### ISSUE THREAD

**Issue by tripleee** [sopython/sopython-site#176]
https://sopython.com/ redirects to https://davidism.com/ and other pages on the site produce an SSL error.
E.g. for https://sopythonc.com/spoiler Chrome shows me `NET::ERR_CERT_COMMON_NAME_INVALID` and says the cert is valid for `davidism.com` but not for `sopython.com`. If I ignore the warning and click through to the site, I get a 404 served by nginx on Ubuntu.

I also left basically the same comments in chat:

https://chat.stackoverflow.com/transcript/message/42137648#42137648

**Comment by davidism** [comment]
I was transfering things from WebFaction to Linode and was in the middle of generating the certs. It's fixed now.
