### ISSUE TITLE
Extract text between two markers example

### ISSUE THREAD

**Issue by mrowan137** [sopython/sopython-site#180]
Hi, I'm not sure exactly the right place to raise this issue but at [https://sopython.com/canon/92/extract-text-from-a-file-between-two-markers/](url) there is a typo in the example: line 7 is currently `        inRecodingMode = False` but should be `        inRecordingMode = False`.

**Comment by davidism** [comment]
Thanks, let someone who has edit privileges know in chat.

**Comment by MattDMo** [comment]
Fixed it
