### ISSUE TITLE
Can't login to sopython

### ISSUE THREAD

**Issue by Ffisegydd** [sopython/sopython-site#34]
Bhargav tried to edit a "Community Mode" wiki post and got 500 Internal Server Error.

He was logged in on the sopython-site and has >100 rep.

http://s7.postimg.org/afqbgelvt/Screenshot_from_2015_02_22_00_50_04.png

**Comment by Ffisegydd** [comment]
I can't re-create this locally at the moment. I've used my account in the DC group to make a wiki page and Bhargav's account to edit it, and it edits it fine. Will question Bhargav a bit more and see if we can pin down the cause in production.

**Comment by Ffisegydd** [comment]
Me and Bhargav have been over things now, I'll try to explain the issue and what I've done so far.

## Bhargav cannot log into sopython.

- He gets a "500 Internal Server Error" whenever he tries to login.
- He's tried to login from different internal pages on the site (wiki, index, etc) and all 500 out.
- He is using "Log in with Google" when he logs in (if that is important, I thought about Google removing openid support, but then again I do the same and I have no issue D:)
- He's tried when in incognito mode and it still 500s out (removal of cookies etc)
- He's revoked permission from the sopython app on http://stackapps.com and then re-given permission, still 500 ISE.

**Comment by robertlagrant** [comment]
This is definitely the least important point, but I think it's *Can't log in to sopython* :)

**Comment by vt6B57** [comment]
FUCK OFF YOURSELF @Ffisegydd @joncle @thefourtheye @mjpieters @poke

**Comment by davidism** [comment]
Same as #36
