### ISSUE TITLE
Stop being so paranoid

### ISSUE THREAD

**Issue by sumeroha** [sopython/sopython-site#38]
I'm writing in reference to [your statement in Python chat](http://chat.stackoverflow.com/transcript/message/21244958#21244958) where you think it's me trolling. Seriously are you so paranoid? I moved on since months. And c'mon would I choose a name like Jambon? Your arrogant avatar doesn't help washing away your paranoy.

Please move on you too and stop being paranoid.

**Comment by sumeroha** [comment]
@mjpieters I would like you to know this too. Acknowledge that I moved on and doing better things than trolling and stop being paranoid. The reason I found about that chat message is because I searched for my name in the chat waiting for paranoid moments like this.

**Comment by sumeroha** [comment]
Okay, I think you get it.

**Comment by sumerohe** [comment]
@mjpieters Stop that really. You know new users can be created. Stop wasting my time with wrong statements and provocations.
